In [ ]:
import pandas as pd
import numpy as np

In [ ]:
combined = pd.read_csv("teamstats1025.csv")
combined.head()

,PTS,opp_PTS,FG,FGA,3P,3PA,2P,2PA,FT,FTA,...,opp_BLK_G,opp_BLK_100poss,opp_TOV_G,opp_TOV_100poss,opp_PF_G,opp_PF_100poss,3PAr,DRB_pct,TRB_pct,FTr
0,2812.0,2105.0,981.0,2010.0,344.0,912.0,637.0,1098.0,506.0,645.0,...,3.117647,4.613309,10.764706,15.928972,16.470588,24.372198,0.453731,0.770306,0.555516,0.320896
1,2392.0,2373.0,840.0,1899.0,271.0,778.0,569.0,1121.0,441.0,601.0,...,3.088235,4.418076,10.558824,15.105613,16.176471,23.142304,0.409689,0.734848,0.514281,0.316482
2,2632.0,2447.0,945.0,2095.0,278.0,886.0,667.0,1209.0,464.0,663.0,...,3.151515,4.404400,12.727273,17.787001,17.333333,24.224201,0.422912,0.730627,0.526852,0.316468
3,2523.0,2282.0,894.0,1995.0,280.0,797.0,614.0,1198.0,455.0,611.0,...,3.939394,5.779094,12.242424,17.959646,16.696970,24.494468,0.399499,0.709961,0.526679,0.306266
4,2515.0,2341.0,884.0,1935.0,254.0,747.0,630.0,1188.0,493.0,646.0,...,3.151515,4.481189,11.575758,16.459753,17.848485,25.379043,0.386047,0.718546,0.497169,0.333850

In [ ]:
leakage = pd.read_csv("SRS_SOS_fixed.csv")

In [ ]:
# leakage["abbr"] = leakage["team"]
leakage["abbr"] = leakage["team"].map(fixes)
# leakage.loc[leakage["team"].isin(fixes),"abbr"].map(fixes)
# leakage.loc[leakage["team"] == "Brigham Young",]
leakage["abbr"] = leakage["abbr"].fillna(leakage["team"])
leakage.to_csv("SRS_SOS_fixed_abbr.csv", index = False)

In [ ]:
def get_caps(s: str) -> str:

    return "".join(c for c in s if c.isupper())

In [ ]:
combined = combined.rename(columns = {"SRS" : "SRS_leak", "SOS" : "SOS_leak"})

In [ ]:
leakage.head(2)

   year       team       MoV    Rating       SOS       SRS       abbr
0  2010  Air Force -8.035714 -3.707022  4.328692 -3.707022  Air Force
1  2010      Akron  4.575758  3.636498 -0.939260  3.636498      Akron

Can you join the "leakage" dataframe and the "combined" dataframe by year and team name? There are different names for both variables; on leakage, those variables are called "year" and "abbr" and they are called "season" and "team" on combined. Exclude the columns "team" and "MoV" from leakage when you join the two. the new dataframe should be called "no_leakage"

In [ ]:
# pd.merge(leakage[["year", "abbr", "Rating", "SOS", "SRS"]], combined,
#          left_on=["year", "abbr"], right_on = ["season", "team"])
no_leakage = pd.merge(combined, leakage[["year", "abbr", "Rating", "SOS", "SRS"]],
         right_on=["year", "abbr"], left_on = ["season", "team"])#.to_csv("no_leakage.csv", index = False)

In [ ]:
matchups = pd.concat([pd.read_csv("matchups25.csv"), pd.read_csv("matchups.csv")]).drop("Unnamed: 0", axis = 1) #.to_csv("matchups1025.csv", index = False)

In [ ]:
no_leakage = pd.read_csv("no_leakage.csv")

In [ ]:
temp = pd.merge(matchups, no_leakage.add_suffix("_team1"), left_on=["season", "team1"], right_on=["season_team1", "team_team1"]).copy()
temp = temp.drop(["abbr_team1", "team_team1", "season_team1", "team_team1", "SRS_leak_team1", "SOS_leak_team1", "Rating_team1"], axis = 1).copy()
pd.merge(temp, no_leakage.add_suffix("_team2"), left_on=["season", "team2"], right_on=["season_team2", "team_team2"])

,season,round,team1,team2,team1_seed,team2_seed,win,PTS_team1,opp_PTS_team1,FG_team1,...,opp_PF_100poss_team2,3PAr_team2,DRB_pct_team2,TRB_pct_team2,FTr_team2,year_team2,abbr_team2,Rating_team2,SOS_team2,SRS_team2
0,2025,64,Duke,Mount St. Mary's,1,16,1,2812.0,2105.0,981.0,...,23.142304,0.409689,0.734848,0.514281,0.316482,2025,Mount St. Mary's,-7.428787,-6.913635,-7.428787
1,2025,64,Mississippi State,Baylor,8,9,0,2632.0,2447.0,945.0,...,24.494468,0.399499,0.709961,0.526679,0.306266,2025,Baylor,19.816149,13.972399,19.816149
2,2025,64,Oregon,Liberty,5,12,1,2515.0,2341.0,884.0,...,21.258057,0.485248,0.756318,0.475395,0.293467,2025,Liberty,8.636770,-0.976133,8.636770
3,2025,64,Arizona,Akron,4,13,1,2779.0,2463.0,977.0,...,22.267567,0.461083,0.745675,0.532431,0.259445,2025,Akron,3.953288,-4.109212,3.953288
4,2025,64,BYU,VCU,6,11,1,2672.0,2339.0,950.0,...,25.140253,0.476049,0.730419,0.548846,0.327901,2025,VCU,15.464730,1.646549,15.464730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,2011,16,UConn,San Diego State,3,2,1,2569.0,2323.0,910.0,...,26.090135,0.300103,0.729779,0.551846,0.320144,2011,San Diego State,18.931551,6.806551,18.931551
878,2011,8,Arizona,UConn,5,3,0,2602.0,2294.0,864.0,...,27.177257,0.292578,0.677952,0.528976,0.343482,2011,UConn,17.702436,10.673865,17.702436
879,2011,4,UConn,Kentucky,3,4,1,2569.0,2323.0,910.0,...,27.150566,0.318750,0.731250,0.534679,0.370833,2011,Kentucky,20.880844,8.305087,20.880844
880,2011,4,VCU,Butler,11,8,0,2432.0,2293.0,825.0,...,29.174869,0.370246,0.751788,0.531918,0.380872,2011,Butler,11.179691,3.695820,11.179691
881,2011,2,UConn,Butler,3,8,1,2569.0,2323.0,910.0,...,29.174869,0.370246,0.751788,0.531918,0.380872,2011,Butler,11.179691,3.695820,11.179691

# scraping 2010

In [1]:
!pip install cloudscraper
import cloudscraper
import urllib3
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from time import sleep
from time import time
import requests
from google.colab import files
from bs4 import Comment
from bs4.element import Tag
# header: str = "https://www.basketball-reference.com"

def soupify(url: str):

    http = urllib3.PoolManager()
    response = http.request('GET', url)
    soup = BeautifulSoup(response.data)

    return soup

def comment_helper(soup, obj: str):

    for comment in soup.find_all(string=lambda string: isinstance(string, Comment)):
        if comment.find(f"<{obj}") > 0: # and comment.find("totals_stats_sh") > 0:
            comment_soup = BeautifulSoup(comment, 'html.parser')
            res = comment_soup.find(obj)

    return res

def comment_helper(soup, obj: str, id = None):

    for comment in soup.find_all(string=lambda string: isinstance(string, Comment)):
        if not id:
            if comment.find(f"<{obj}") > 0:
                comment_soup = BeautifulSoup(comment, 'html.parser')
                res = comment_soup.find(obj)
        else:
            if comment.find(f"<{obj}") > 0 and comment.find(id) > 0:
                comment_soup = BeautifulSoup(comment, 'html.parser')
                res = comment_soup.find(obj)

    return res

def soupify_with_cloudscraper(url):
    scraper = cloudscraper.create_scraper()
    response = scraper.get(url)
    return BeautifulSoup(response.text, 'html.parser')

def get_table_ids(soup: "BeautifulSoup") -> list[str]:

    return list(t.get('id') for t in soup.find_all('table') if t.get('id'))

def get_columns(table_soup: "BeautifulSoup") -> list[str]:

    return list(t.get('data-stat') for t in table_soup.find('thead').find_all('th'))

Collecting cloudscraper
  Downloading cloudscraper-1.2.71-py2.py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.12/dist-packages (from cloudscraper) (3.3.2)
Requirement already satisfied: requests>=2.9.2 in /usr/local/lib/python3.12/dist-packages (from cloudscraper) (2.32.4)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from cloudscraper) (1.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper) (2026.5.20)
Downloading cloudscraper-1.2.71-py2.py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 4.2 MB/s eta 0:00:00
Installing collected packages: cloudscraper
Successfully installed cloudscraper-1.2.71

In [2]:
year: int = 2010
url: str = f"https://www.sports-reference.com/cbb/postseason/men/{year}-ncaa.html"
s = soupify_with_cloudscraper(url)

In [ ]:
header: str = "https://sports-reference.com"
urls = {}
for team in s.find('div', {"id" : "brackets"}).find_all('a'):
    if "schools" in team.get('href'):
        if team.contents[0] not in urls:
            urls[team.contents[0]] = header + team["href"].replace("2010", "2010-gamelogs")

In [ ]:
# Extract 'item' from each 'sublist' in 'nested_list'
# flat_list = [item for sublist in nested_list for item in sublist]

In [ ]:
[1,2,3,4,5][:1] + [1,2,3,4,5][2:]

[1, 3, 4, 5]

In [ ]:
nec = list(d.find_all('a') for d in s.find('div', {"id" : "brackets"}).find_all('div') if not d.find('p'))
all_teams = list(item for L in nec for item in L if "schools" in item["href"])
# list(t for t in s.find('div', {"id" : "brackets"}).find_all('span'))
apps = {team.contents[0]:header + team["href"].replace("2010", "2010-gamelogs") for team in all_teams}
len(apps)

64

In [3]:
def get_tourney_teams(bracket_page, year, header = "https://sports-reference.com"):

    nec = list(d.find_all('a') for d in bracket_page.find('div', {"id" : "brackets"}).find_all('div') if not d.find('p'))
    all_teams = list(item for L in nec for item in L if "schools" in item["href"])
    apps = {team.contents[0]:header + team["href"].replace(f"{year}", f"{year}-gamelogs") for team in all_teams}

    return apps

In [4]:
urls = get_tourney_teams(s, year)
len(urls)

64

In [ ]:
no_leakage.columns[:40]

Index(['PTS', 'opp_PTS', 'FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'opp_FG',
       'opp_FGA', 'opp_3P', 'opp_3PA', 'opp_2P', 'opp_2PA', 'opp_FT',
       'opp_FTA', 'opp_ORB', 'opp_DRB', 'opp_TRB', 'opp_AST', 'opp_STL',
       'opp_BLK', 'opp_TOV', 'opp_PF', 'team', 'season', 'G', 'SRS_leak',
       'SOS_leak', 'FG%'],
      dtype='object')

In [16]:
first_year = 2010
start = time()
for year in range(2010, 2011):
    url: str = f"https://www.sports-reference.com/cbb/postseason/men/{year}-ncaa.html"
    s = soupify_with_cloudscraper(url)
    sleep(5)
    urls = get_tourney_teams(s, year)
    for team in list(urls):
        log = soupify_with_cloudscraper(urls[team])
        t = log.find('table', {"id" : "team_game_log"})
        # if team == next(iter(urls)):
        if year == first_year and team == next(iter(urls)):
            cols = list(c for c in get_columns(t)[14:] if "pct" not in c)
            df = pd.DataFrame(columns = ["year", "team","G", "MP", "pts", "opp_pts"] + cols)
        tracker = {c:0 for c in cols}
        pts = 0
        opp_pts = 0
        mins = 0
        games = 0
        for game in t.find('tbody').find_all('tr'):
            if game.find('td'):
                if game.find('td', {"data-stat" : "opp_name_abbr"}).find('a'):
                    if any(y in game.find('td', {"data-stat" : "game_type"}).contents[0] for y in {"REG", "CTOURN"}):
                        if game.find('td', {"data-stat" : "opp_fg"}).contents:
                            tracker = {col: float(game.find('td', {"data-stat" : col}).contents[0]) + tracker[col] for col in cols}
                            pts += int(game.find('td', {"data-stat" : "team_game_score"}).contents[0])
                            opp_pts += int(game.find('td', {'data-stat' : "opp_team_game_score"}).contents[0])
                            games += 1
                            mins += 40
                            if game.find('td', {"data-stat" : "overtimes"}).contents:
                                OT = game.find('td', {"data-stat" : "overtimes"}).contents[0]
                                if OT[0].isnumeric():
                                    mins += int(OT[0])*5
                                else:
                                    mins += 5
                        else:
                            print([year, team,
                                  # game.find('td', {"data-stat" : "team_game_num_season"}).contents[0]])
                                  game.find('td', {"data-stat" : "opp_name_abbr"}).find('a').contents[0],
                                  game.find('td', {"data-stat" : "date"}).contents[0]
                            ])
                    else:
                        break
        df.loc[len(df.index)] = [year, team, games, mins, pts, opp_pts] + list(tracker.values())
        sleep(5)
    print(f"{year} done, time elapsed: {time() - start}")

[2010, 'Temple', 'Richmond', '2010-03-14']
[2010, 'Wofford', 'Appalachian State', '2010-03-08']
[2010, 'Lehigh', 'Lafayette', '2010-03-12']
[2010, 'Northern Iowa', 'Wichita State', '2010-03-07']
[2010, 'Houston', 'Oklahoma', '2009-11-26']
[2010, 'Houston', 'UTEP', '2010-03-13']
[2010, 'Georgia Tech', 'Duke', '2010-03-14']
[2010, 'Ohio State', 'Minnesota', '2010-03-14']
[2010, 'Duke', 'Georgia Tech', '2010-03-14']
[2010, 'Arkansas-Pine Bluff', 'Alabama State', '2010-01-11']
[2010, 'Arkansas-Pine Bluff', 'Alabama A&M', '2010-02-06']
[2010, 'Sam Houston', 'Stephen F. Austin', '2010-03-13']
[2010, 'Richmond', 'Temple', '2010-03-14']
[2010, 'Robert Morris', 'Quinnipiac', '2010-03-10']
[2010, 'Vermont', 'Boston University', '2010-03-13']
[2010, 'Butler', 'Wright State', '2010-03-09']
[2010, 'UTEP', 'Houston', '2010-03-13']
[2010, 'Murray State', 'Morehead State', '2010-03-06']
[2010, 'Minnesota', 'Ohio State', '2010-03-14']
[2010, 'Oakland', 'IUPUI', '2010-03-09']
[2010, 'North Texas', 'Troy', '2010-03-09']
2010 done, time elapsed: 365.62157440185547

In [17]:
df

,year,team,G,MP,pts,opp_pts,fg,fga,fg3,fg3a,...,opp_ft,opp_fta,opp_orb,opp_drb,opp_trb,opp_ast,opp_stl,opp_blk,opp_tov,opp_pf
0,2010,Kentucky,34,1375,2694,2219,952.0,1988.0,203.0,595.0,...,405.0,578.0,433.0,587.0,1020.0,373.0,233.0,106.0,478.0,707.0
1,2010,ETSU,33,1325,2278,2191,808.0,1861.0,169.0,538.0,...,467.0,705.0,399.0,661.0,1060.0,422.0,238.0,117.0,552.0,622.0
2,2010,Texas,33,1330,2681,2300,979.0,2089.0,187.0,542.0,...,489.0,713.0,415.0,587.0,1002.0,377.0,245.0,122.0,496.0,692.0
3,2010,Wake Forest,29,1185,2116,1985,760.0,1735.0,126.0,402.0,...,473.0,678.0,405.0,600.0,1005.0,322.0,205.0,111.0,410.0,606.0
4,2010,Temple,33,1330,2152,1857,805.0,1843.0,193.0,574.0,...,341.0,487.0,330.0,660.0,990.0,323.0,174.0,100.0,376.0,544.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2010,Oakland,31,1240,2331,2231,807.0,1817.0,180.0,558.0,...,394.0,584.0,349.0,590.0,939.0,394.0,212.0,110.0,399.0,622.0
60,2010,BYU,33,1320,2726,2167,937.0,1944.0,268.0,645.0,...,454.0,673.0,327.0,634.0,961.0,409.0,192.0,95.0,515.0,606.0
61,2010,Florida,33,1325,2363,2159,856.0,1928.0,193.0,616.0,...,342.0,508.0,386.0,623.0,1009.0,428.0,215.0,133.0,453.0,567.0
62,2010,Kansas State,32,1290,2543,2215,840.0,1873.0,215.0,603.0,...,574.0,828.0,381.0,582.0,963.0,383.0,229.0,112.0,546.0,784.0
63,2010,North Texas,29,1180,2138,2034,699.0,1522.0,154.0,463.0,...,405.0,568.0,328.0,520.0,848.0,326.0,209.0,112.0,378.0,661.0

In [ ]:
def google_search(query: str, site: str) -> str:

    # print(f"from:{site}.com {query}")

    # return None
    return f"from:{site}.com {query}"

google_search("Northern Colorado 2011 basketball game log", "sports-reference")

'from:sports-reference.com Northern Colorado 2011 basketball game log'

In [19]:
df.to_csv("teamstats10_PREFIX_d1.csv", index = False)

In [ ]:
df.to_csv("teamstats10.csv", index = False)

In [ ]:
import pandas as pd

In [ ]:
df10 = pd.read_csv("teamstats10_d1.csv")
to_add = pd.read_csv("to_add.csv")

df10["pts"] = df10["ft"] + 2*df10["fg2"] + 3*df10["fg3"]
df10["opp_pts"] = df10["opp_ft"] + 2*df10["opp_fg2"] + 3*df10["opp_fg3"]

In [ ]:
list(t for t in to_add["team"].values if t not in df10["team"].values)

[]

In [ ]:
df10.loc[df10["team"].isin(list(to_add["team"].values)),]

,year,team,G,MP,fg,fga,fg3,fg3a,fg2,fg2a,...,opp_orb,opp_drb,opp_trb,opp_ast,opp_stl,opp_blk,opp_tov,opp_pf,pts,opp_pts
4,2010,Temple,33,1330,805.0,1843.0,193.0,574.0,612.0,1269.0,...,330.0,660.0,990.0,323.0,174.0,100.0,376.0,544.0,2152.0,1857.0
7,2010,Wofford,32,1285,758.0,1719.0,189.0,544.0,569.0,1175.0,...,313.0,642.0,955.0,311.0,165.0,124.0,457.0,626.0,2222.0,1991.0
17,2010,Lehigh,31,1250,790.0,1736.0,206.0,513.0,584.0,1223.0,...,334.0,644.0,978.0,450.0,205.0,101.0,427.0,639.0,2330.0,2182.0
19,2010,Northern Iowa,31,1240,668.0,1551.0,201.0,578.0,467.0,973.0,...,243.0,580.0,823.0,271.0,141.0,59.0,376.0,566.0,1959.0,1685.0
23,2010,Houston,31,1250,849.0,2044.0,250.0,719.0,599.0,1325.0,...,414.0,802.0,1216.0,410.0,144.0,107.0,524.0,566.0,2420.0,2312.0
29,2010,Georgia Tech,32,1285,846.0,1860.0,193.0,527.0,653.0,1333.0,...,448.0,568.0,1016.0,424.0,255.0,107.0,487.0,614.0,2332.0,2116.0
30,2010,Ohio State,33,1330,878.0,1778.0,237.0,620.0,641.0,1158.0,...,321.0,634.0,955.0,408.0,167.0,65.0,469.0,595.0,2434.0,2020.0
32,2010,Duke,33,1320,883.0,1996.0,252.0,655.0,631.0,1341.0,...,388.0,577.0,965.0,361.0,177.0,128.0,486.0,649.0,2586.0,2037.0
33,2010,Arkansas-Pine Bluff,30,1215,649.0,1570.0,123.0,407.0,526.0,1163.0,...,270.0,573.0,843.0,353.0,237.0,125.0,427.0,629.0,1926.0,1940.0
43,2010,Sam Houston,27,1090,743.0,1592.0,245.0,630.0,498.0,962.0,...,289.0,559.0,848.0,465.0,173.0,89.0,410.0,576.0,2173.0,1977.0
44,2010,Richmond,33,1350,820.0,1837.0,235.0,664.0,585.0,1173.0,...,438.0,706.0,1144.0,326.0,181.0,112.0,506.0,597.0,2304.0,2060.0
47,2010,Robert Morris,33,1320,773.0,1765.0,187.0,511.0,586.0,1254.0,...,368.0,599.0,967.0,402.0,227.0,108.0,518.0,666.0,2277.0,2183.0
49,2010,Vermont,33,1325,777.0,1773.0,153.0,488.0,624.0,1285.0,...,411.0,602.0,1013.0,356.0,230.0,121.0,457.0,731.0,2318.0,2118.0
52,2010,Butler,31,1245,703.0,1560.0,207.0,613.0,496.0,947.0,...,268.0,562.0,830.0,332.0,161.0,98.0,422.0,651.0,2173.0,1876.0
53,2010,UTEP,31,1255,842.0,1764.0,193.0,552.0,649.0,1212.0,...,361.0,634.0,995.0,344.0,176.0,75.0,501.0,584.0,2352.0,1973.0
55,2010,Murray State,31,1240,838.0,1680.0,195.0,522.0,643.0,1158.0,...,376.0,462.0,838.0,340.0,199.0,89.0,515.0,579.0,2373.0,1902.0
57,2010,Minnesota,33,1335,871.0,1835.0,232.0,575.0,639.0,1260.0,...,381.0,565.0,946.0,428.0,216.0,86.0,480.0,578.0,2418.0,2087.0
59,2010,Oakland,31,1240,807.0,1817.0,180.0,558.0,627.0,1259.0,...,349.0,590.0,939.0,394.0,212.0,110.0,399.0,622.0,2331.0,2231.0
63,2010,North Texas,29,1180,699.0,1522.0,154.0,463.0,545.0,1059.0,...,328.0,520.0,848.0,326.0,209.0,112.0,378.0,661.0,2138.0,2034.0

In [ ]:
to_add.columns

Index(['year', 'date', 'team', 'opp', 'G', 'MP', 'fg', 'fga', 'fg3', 'fg3a',
       'fg2', 'fg2a', 'ft', 'fta', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk',
       'tov', 'pf', 'pts', 'opp_fg', 'opp_fga', 'opp_fg3', 'opp_fg3a',
       'opp_fg2', 'opp_fg2a', 'opp_ft', 'opp_fta', 'opp_orb', 'opp_drb',
       'opp_trb', 'opp_ast', 'opp_stl', 'opp_blk', 'opp_tov', 'opp_pf',
       'opp_pts'],
      dtype='object')

In [ ]:
for row in range(len(to_add)):
    team = to_add.iloc[row]["team"]
    for col in to_add.columns[4:]:
        df10.loc[df10["team"] == team, col] += to_add.iloc[0][col]

In [ ]:
# df10.loc[df10["team"].isin(list(to_add["team"].values)),]
df10.to_csv("teamstats10_d1.csv", index = False)

In [ ]:
df = pd.read_csv("teamstats11-26_d1.csv")
df["pts"] = df["ft"] + 2*df["fg2"] + 3*df["fg3"]
df["opp_pts"] = df["opp_ft"] + 2*df["opp_fg2"] + 3*df["opp_fg3"]

In [ ]:
df = pd.concat([df10, df]).copy()

In [ ]:
df[list(c for c in to_add.columns if c in df.columns)].to_csv("teamstats10-26_d1.csv", index = False)

In [ ]:
leakage = pd.read_csv("SRS_SOS_fixed_abbr.csv")

In [ ]:
set(t for t in leakage["abbr2"].values if "UCSB" in t)

KeyError: 'abbr2'

In [ ]:
fixes = {"McNeese State" : "McNeese",
          "UC-Irvine" : "UC Irvine",
         "UC-Davis" : "UC Davis",
         "UC-San Diego" : "UC San Diego",
         "UCSB" : "UC Santa Barbara",
         "St. Joseph's" : "Saint Joseph's",
         "St. Peter's" : "Saint Peter's"
          }

In [ ]:
# leakage["abbr"] = leakage["team"]
leakage["abbr2"] = leakage["abbr"].map(fixes)
# leakage.loc[leakage["team"].isin(fixes),"abbr"].map(fixes)
# leakage.loc[leakage["team"] == "Brigham Young",]
leakage["abbr2"] = leakage["abbr2"].fillna(leakage["abbr"])

In [ ]:
set(t for t in df["team"].values if t not in leakage["abbr2"].values)

set()

In [ ]:
cols = ["year", "team", "SRS", "SOS"] + list(to_add.columns[4:])

In [ ]:
final = pd.merge(leakage[["year","abbr2", "SRS", "SOS"]], df,
         left_on = ["year", "abbr2"], right_on = ["year", "team"]).drop("team", axis = 1).rename(columns = {"abbr2" : "team"}).copy()
final[cols].to_csv("df_noLeaks_10-26.csv", index = False)